//! Cloudflare Workers host for rustcfml.org.
//!
//! The site's templates are embedded by `build.rs`; everything under
//! `assets/` is served by Workers Static Assets before a request ever
//! reaches this code.
//!
//! The Worker host does not read `urlrewrite.xml`, so [`resolve`] ports those
//! rules: clean URLs, the private-path block, and the styled 404 page. The
//! rewrite happens here rather than in the engine because
//! `cfml_worker::handle_fetch` answers an unresolvable path with a bare
//! "Not Found" string, and this site has a 404 page of its own.

#![cfg(target_arch = "wasm32")]

use worker::*;

// Generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/embedded_files.rs"));

/// Filesystem root the VM sees. `CFML_FILES` paths are relative to it.
const VIRTUAL_ROOT: &str = "/app";

/// Must match `this.name` in Application.cfc.
const APP_NAME: &str = "RustCFMLSite";

const NOT_FOUND: &str = "/404.cfm";

fn embedded(rel: &str) -> bool {
    CFML_FILES.iter().any(|(path, _)| *path == rel)
}

/// Paths the document root must never expose, mirroring rule 1 of
/// urlrewrite.xml.
fn is_private(rel: &str) -> bool {
    let rel = rel.to_ascii_lowercase();
    rel == "application.cfc"
        || rel == "urlrewrite.xml"
        || ["logs/", "includes/", "lib/", "tools/"]
            .iter()
            .any(|prefix| rel.starts_with(prefix))
}

/// A URL segment that may stand in for a template name: lowercase, digits and
/// hyphens only. `alpha_first` is the stricter form rule 3 asks for.
fn is_slug(segment: &str, alpha_first: bool) -> bool {
    let mut chars = segment.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    let first_ok = if alpha_first {
        first.is_ascii_lowercase()
    } else {
        first.is_ascii_lowercase() || first.is_ascii_digit()
    };
    first_ok
        && segment
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
}

/// Maps a request path to the template that answers it. Always returns a
/// template that exists, so the engine never has to produce its own 404.
fn resolve(path: &str) -> String {
    let trimmed = path.trim_end_matches('/');
    if trimmed.is_empty() {
        return "/index.cfm".to_string();
    }

    let rel = trimmed.trim_start_matches('/');
    if is_private(rel) {
        return NOT_FOUND.to_string();
    }
    if embedded(rel) {
        return format!("/{rel}");
    }

    let mut segments = rel.split('/');
    let first = segments.next().unwrap_or_default();
    let second = segments.next();
    if segments.next().is_some() {
        return NOT_FOUND.to_string();
    }
    let template = format!("{first}.cfm");
    if !embedded(&template) {
        return NOT_FOUND.to_string();
    }

    match second {
        // /features -> /features.cfm
        None if is_slug(first, false) => format!("/{template}"),
        // /community/contributing -> /community.cfm/contributing, as path info
        Some(sub) if is_slug(first, true) && !sub.is_empty() && !sub.contains('.') => {
            format!("/{template}/{sub}")
        }
        _ => NOT_FOUND.to_string(),
    }
}

fn build_config() -> cfml_worker::WorkerConfig {
    let mut config = cfml_worker::WorkerConfig::new(CFML_FILES, VIRTUAL_ROOT);
    config.app_names = vec![APP_NAME.to_string()];
    // Cache compiled bytecode per isolate. The site is read-only, so there is
    // nothing to invalidate between requests.
    config.production_mode = true;
    config
}

#[event(fetch)]
pub async fn fetch(req: Request, env: Env, ctx: Context) -> Result<Response> {
    let config = build_config();

    let mut url = req.url()?;

    // One canonical hostname. sitemap.xml and robots.txt both name the apex,
    // so www is answered only to send visitors there, path and query intact.
    if let Some(apex) = url.host_str().and_then(|h| h.strip_prefix("www.")) {
        let apex = apex.to_string();
        url.set_host(Some(&apex))?;
        return Response::redirect_with_status(url, 301);
    }

    let target = resolve(url.path());
    if target == url.path() {
        return cfml_worker::handle_fetch(req, env, ctx, &config).await;
    }

    url.set_path(&target);
    let mut init = RequestInit::new();
    init.with_method(req.method()).with_headers(req.headers().clone());
    let rewritten = Request::new_with_init(url.as_str(), &init)?;
    cfml_worker::handle_fetch(rewritten, env, ctx, &config).await
}

/// Required even though no cron trigger is configured: `jspi-patch.mjs` wraps
/// both the `fetch` and `scheduled` wasm exports in `WebAssembly.promising`,
/// and a missing `scheduled` export fails the build (and would throw at module
/// load). Wired to the real sweeper rather than left empty, so adding a cron
/// trigger and a SESSIONS binding is all it would take to expire sessions.
#[event(scheduled)]
pub async fn scheduled(event: ScheduledEvent, env: Env, ctx: ScheduleContext) {
    let config = build_config();
    let _ = cfml_worker::handle_scheduled(event, env, ctx, &config).await;
}

// Kept from the reference host: the post-build patch wraps these in
// `WebAssembly.promising`, and re-exporting stops wasm-opt dropping them.
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn cfml_worker_run_sync() {
    cfml_worker::sync_runner::cfml_worker_run_sync();
}

#[wasm_bindgen]
pub fn cfml_worker_jspi_smoke() {
    cfml_worker::jspi_smoke::cfml_worker_jspi_smoke();
}

#[wasm_bindgen]
pub fn cfml_worker_jspi_smoke_take() -> String {
    cfml_worker::jspi_smoke::cfml_worker_jspi_smoke_take()
}
